---
title: "Looking at S_c and G_c"
author: "Claire Powers"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

library(tidyverse)
library(MASS)
source("./functions/logit2prob.R")

szs = c(1,5,10)
```


```{r survival}
s.aspect = matrix(c(-1,0,1,
                  -1,0,1,
                  -1,0,1),nrow=3,byrow = T)


survs = c(0.1,0.45,0.65) 
survs_lm = glm(survs~szs,family = binomial)

S_a = survs_lm$coefficients[1]
S_b = survs_lm$coefficients[2]
S_c = c(0.06,0.01,0.02)
S_d = c(-0.025,-0.015,-0.015)
e = 1
clim = 0

# Look at clim valsv
# S_c = 0.02
# S_d = -0.025

climdf = data.frame(clim=seq(-3,3,length.out=99),
                    aspect = rep(c("N","T","S"),33),
                    S.s=NA,
                    S.j=NA,
                    S.a=NA)

loopseq = seq(1,99,3)

for(i in loopseq){

  clim = climdf$clim[i]
  survival = logit2prob(S_a + S_b*szs + S_c*(clim + e*s.aspect) + S_d*(clim + e*s.aspect)^2)

  climdf[i:(i+2),3:5] = t(survival)
  rm(survival)
}

ggplot(climdf,aes(x=clim))+
  geom_point(aes(y=S.s,color=aspect))+
  geom_line(aes(y=S.s,color=aspect))+
  geom_point(aes(y=S.j,color=aspect))+
  geom_line(aes(y=S.j,color=aspect))+
  geom_point(aes(y=S.a,color=aspect))+
  geom_line(aes(y=S.a,color=aspect))+
  theme_bw()+
  geom_vline(xintercept = 0)+
  #facet_wrap(~aspect)+
  ylim(0,0.8)

```

```{r growth}
# Columns = (N,top,S)
g.aspect = matrix(c(-1,0,1,
                    -1,0,1),
                  nrow=2,byrow=T)


growth = c(0.35,0.65) 
grow_lm = glm(growth~szs[1:2])

G_a = grow_lm$coefficients[1]
G_b = grow_lm$coefficients[2]

G_c = c(0.003,0.003)
G_d = c(-0.005,-0.003)
e = 1
clim = 2

climdf = data.frame(clim=seq(-2.5,2.5,length.out=99),
                    aspect = rep(c("N","T","S"),33),
                    G.s=NA,
                    G.j=NA)

loopseq = seq(1,99,3)

for(i in loopseq){

  clim = climdf$clim[i]
  growth = G_a + G_b*szs[1:2] + G_c*(clim + e*g.aspect) + G_d*(clim + e*g.aspect)^2

  climdf[i:(i+2),3:4] = t(growth)
  rm(growth)
}

ggplot(climdf,aes(x=clim))+
  geom_point(aes(y=G.s,color=aspect))+
  geom_line(aes(y=G.s,color=aspect))+
  geom_point(aes(y=G.j,color=aspect))+
  geom_line(aes(y=G.j,color=aspect))+
  theme_bw()+
  geom_vline(xintercept = c(-2,0,2))+
  ylim(0,0.8)
```


# Baseline fecundity
```{r F}

clim=0
e = 1
s.aspect=0
S_rates = logit2prob(S_a + S_b*szs + S_c*(clim + e*s.aspect) + S_d*(clim + e*s.aspect)^2)

g.aspect=0
G_rates = G_a + G_b*szs[1:2] + G_c*(clim + e*g.aspect) + G_d*(clim + e*g.aspect)^2

S.sdlg = S_rates[1]
S.juv = S_rates[2]
S.adult = S_rates[3]

G.sdlg = G_rates[1]
G.juv = G_rates[2]

base_mx = matrix(rep(0,9),nrow=3)
base_mx[2,1] = S.sdlg*G.sdlg

base_mx[2,2] = S.juv*(1-G.juv)
base_mx[3,2] = S.juv*G.juv

base_mx[3,3] = S.adult

F_fun <- function(F){
      base_mx[1,3] <- F*S.adult*S.sdlg
      lam <- Re(eigen(base_mx)$values[1])
      x = (1-lam)^2
      return(x)
}

Fec <- optim(par = 500, fn = F_fun,method = "L-BFGS-B", lower=0, upper=100000)
Fec <- round(Fec$par)

base_mx[1,3] <- Fec*S.adult*S.sdlg
Re(eigen(base_mx)$values[1]) # = 1.000139
```
